set(impl_h
pointeditorpresenterimpl.h
cartpresenterimpl.h
planningpresenterimpl.h
patientsdatabaseimpl.h
patientsmodel.h
popupspresenterimpl.h
loginpresenterimpl.h
)

set(impl_cpp
pointeditorpresenterimpl.cpp
cartpresenterimpl.cpp
planningpresenterimpl.cpp
patientsdatabaseimpl.cpp
patientsmodel.cpp
popupspresenterimpl.cpp
loginpresenterimpl.cpp
)
