#include "presenters.h"

#include <greenhousecontext.h>

// AUTOGENERATED HEADERS, DONT REMOVE THIS LINE
#include "popupspresenterimpl.h"
#include "loginpresenterimpl.h"

Presenters::Presenters(QObject *parent)
    : QObject(parent)
    , ApplicationPluginInterface()
{
}

void Presenters::populateContext(GreenHouse::Context *context)
{
    // AUTOGENERATED IMPLEMENTATIONS, DONT REMOVE THIS LINE
    auto popupsPresenter = new PopupsPresenterImpl;

    context->store(popupsPresenter);
    context->store(new LoginPresenterImpl(popupsPresenter));
}

void Presenters::resolveDependencies(GreenHouse::Context *)
{
    // NOTE: This is where you can query the context for dependencies
    // SampleObject *sample = context->get<SampleObject>();
}
