//--------------------------------------------------------------------------------------------------
// Generated using GreenHouse Modeling Library v 1.6.15
// From: ZetaSurgical KeyboardPresenter Interface
// Please do not edit this file as it will be overwritten the next time the application flow is
// regenerated.
//--------------------------------------------------------------------------------------------------
#pragma once

#include <limits>

#include <QCoreApplication>

#include <gtest/gtest.h>
#include <gmock/gmock-matchers.h>

#include <QJsonDocument>

#include <applicationpluginmanager.h>

#include <ZetaSurgical/keyboardpresenter.hpp>

using namespace testing;

class KeyboardPresenterImplTestRpc : public GreenHouse::RPCServiceInterface
{
public:
    using GreenHouse::RPCServiceInterface::RPCServiceInterface;

    QList<QJsonObject> messages;

    // GreenHouse::RPCServiceInterface interface
protected:
    void sendPayload(const QByteArray &data) override
    {
        QJsonParseError err;
        QJsonDocument doc = QJsonDocument::fromJson(data, &err);
        if (err.error == QJsonParseError::NoError) {
            messages.append(doc.object());
        }
    }
};

class KeyboardPresenterInterfaceImplTest : public Test
{
    // Test interface
protected:
    void SetUp();
    void TearDown();

    ZetaSurgical::KeyboardPresenter *iface;
    ApplicationPluginManager *m_applicationPluginManager;
    KeyboardPresenterImplTestRpc *m_rpc;
    GreenHouse::Context m_ctx;
};

void KeyboardPresenterInterfaceImplTest ::SetUp()
{
    m_rpc = new KeyboardPresenterImplTestRpc(&m_ctx);
    QDir pluginDir;
    pluginDir = QDir(qApp->applicationDirPath());
    pluginDir.cdUp();
    pluginDir.cdUp();
    pluginDir.cd(QStringLiteral("plugins"));
    m_applicationPluginManager = new ApplicationPluginManager(pluginDir.absoluteFilePath(QStringLiteral("config.json")),
                                                              pluginDir.absolutePath());
    if (m_applicationPluginManager)
        m_applicationPluginManager->inject(&m_ctx);
    iface = m_ctx.get<ZetaSurgical::KeyboardPresenter>();
    if (!iface) {
        iface = new ZetaSurgical::KeyboardPresenter;
        m_ctx.store(iface);
    }
    m_ctx.startExecution();
}

void KeyboardPresenterInterfaceImplTest ::TearDown()
{
    delete m_applicationPluginManager;
}

TEST_F(KeyboardPresenterInterfaceImplTest, onBackspaceClicked)
{

    iface->onBackspaceClicked();
}

TEST_F(KeyboardPresenterInterfaceImplTest, onCharacterButtonClicked)
{

    iface->onCharacterButtonClicked(QString());
}

TEST_F(KeyboardPresenterInterfaceImplTest, onCleanClicked)
{

    iface->onCleanClicked();
}

TEST_F(KeyboardPresenterInterfaceImplTest, onCopyClicked)
{

    iface->onCopyClicked();
}

TEST_F(KeyboardPresenterInterfaceImplTest, onEnterClicked)
{

    iface->onEnterClicked();
}

TEST_F(KeyboardPresenterInterfaceImplTest, onLeftArrowClicked)
{

    iface->onLeftArrowClicked();
}

TEST_F(KeyboardPresenterInterfaceImplTest, onPasteClicked)
{

    iface->onPasteClicked();
}

TEST_F(KeyboardPresenterInterfaceImplTest, onRightArrowClicked)
{

    iface->onRightArrowClicked();
}

TEST_F(KeyboardPresenterInterfaceImplTest, onShiftClicked)
{

    iface->onShiftClicked();
}

TEST_F(KeyboardPresenterInterfaceImplTest, onShiftLockClicked)
{

    iface->onShiftLockClicked();
}

TEST_F(KeyboardPresenterInterfaceImplTest, onSpaceClicked)
{

    iface->onSpaceClicked();
}

TEST_F(KeyboardPresenterInterfaceImplTest, onTabulationClicked)
{

    iface->onTabulationClicked();
}
