//--------------------------------------------------------------------------------------------------
// Generated using GreenHouse Modeling Library v 1.6.15
// From: ZetaSurgical CartPresenter Interface
// Please do not edit this file as it will be overwritten the next time the application flow is
// regenerated.
//--------------------------------------------------------------------------------------------------
#pragma once

#include <limits>

#include <QCoreApplication>

#include <gtest/gtest.h>
#include <gmock/gmock-matchers.h>

#include <QJsonDocument>

#include <applicationpluginmanager.h>

#include <ZetaSurgical/cartpresenter.hpp>

using namespace testing;

class CartPresenterImplTestRpc : public GreenHouse::RPCServiceInterface
{
public:
    using GreenHouse::RPCServiceInterface::RPCServiceInterface;

    QList<QJsonObject> messages;

    // GreenHouse::RPCServiceInterface interface
protected:
    void sendPayload(const QByteArray &data) override
    {
        QJsonParseError err;
        QJsonDocument doc = QJsonDocument::fromJson(data, &err);
        if (err.error == QJsonParseError::NoError) {
            messages.append(doc.object());
        }
    }
};

class CartPresenterInterfaceImplTest : public Test
{
    // Test interface
protected:
    void SetUp();
    void TearDown();

    ZetaSurgical::CartPresenter *iface;
    ApplicationPluginManager *m_applicationPluginManager;
    CartPresenterImplTestRpc *m_rpc;
    GreenHouse::Context m_ctx;
};

void CartPresenterInterfaceImplTest ::SetUp()
{
    m_rpc = new CartPresenterImplTestRpc(&m_ctx);
    QDir pluginDir;
    pluginDir = QDir(qApp->applicationDirPath());
    pluginDir.cdUp();
    pluginDir.cdUp();
    pluginDir.cd(QStringLiteral("plugins"));
    m_applicationPluginManager = new ApplicationPluginManager(pluginDir.absoluteFilePath(QStringLiteral("config.json")),
                                                              pluginDir.absolutePath());
    if (m_applicationPluginManager)
        m_applicationPluginManager->inject(&m_ctx);
    iface = m_ctx.get<ZetaSurgical::CartPresenter>();
    if (!iface) {
        iface = new ZetaSurgical::CartPresenter;
        m_ctx.store(iface);
    }
    m_ctx.startExecution();
}

void CartPresenterInterfaceImplTest ::TearDown()
{
    delete m_applicationPluginManager;
}

TEST_F(CartPresenterInterfaceImplTest, wheelsAreLocked_Imp)
{
    auto oldValue = iface->wheelsAreLocked();
    auto newValue = !oldValue;

    bool changeSignalEmitted = false;
    QObject::connect(iface, &ZetaSurgical::CartPresenter::wheelsAreLockedChanged,
                     [&]() { changeSignalEmitted = true; });

    iface->setWheelsAreLocked(newValue);
    ASSERT_TRUE(changeSignalEmitted);
    ASSERT_NE(iface->wheelsAreLocked(), oldValue);
    ASSERT_EQ(iface->wheelsAreLocked(), newValue);
}

TEST_F(CartPresenterInterfaceImplTest, cameraToFaceDistanceString_Imp)
{
    auto oldValue = iface->cameraToFaceDistanceString();
    auto newValue = QStringLiteral("Lorem Ipsum Test STR");

    bool changeSignalEmitted = false;
    QObject::connect(iface, &ZetaSurgical::CartPresenter::cameraToFaceDistanceStringChanged,
                     [&]() { changeSignalEmitted = true; });

    iface->setCameraToFaceDistanceString(newValue);
    ASSERT_TRUE(changeSignalEmitted);
    ASSERT_NE(iface->cameraToFaceDistanceString(), oldValue);
    ASSERT_EQ(iface->cameraToFaceDistanceString(), newValue);
}
