//--------------------------------------------------------------------------------------------------
// Generated using GreenHouse Modeling Library v 1.6.15
// From: ZetaSurgical PlanningPresenter Interface
// Please do not edit this file as it will be overwritten the next time the application flow is
// regenerated.
//--------------------------------------------------------------------------------------------------
#pragma once

#include <limits>

#include <QCoreApplication>

#include <gtest/gtest.h>
#include <gmock/gmock-matchers.h>

#include <QJsonDocument>

#include <applicationpluginmanager.h>

#include <ZetaSurgical/planningpresenter.hpp>

using namespace testing;

class PlanningPresenterImplTestRpc : public GreenHouse::RPCServiceInterface
{
public:
    using GreenHouse::RPCServiceInterface::RPCServiceInterface;

    QList<QJsonObject> messages;

    // GreenHouse::RPCServiceInterface interface
protected:
    void sendPayload(const QByteArray &data) override
    {
        QJsonParseError err;
        QJsonDocument doc = QJsonDocument::fromJson(data, &err);
        if (err.error == QJsonParseError::NoError) {
            messages.append(doc.object());
        }
    }
};

class PlanningPresenterInterfaceImplTest : public Test
{
    // Test interface
protected:
    void SetUp();
    void TearDown();

    ZetaSurgical::PlanningPresenter *iface;
    ApplicationPluginManager *m_applicationPluginManager;
    PlanningPresenterImplTestRpc *m_rpc;
    GreenHouse::Context m_ctx;
};

void PlanningPresenterInterfaceImplTest ::SetUp()
{
    m_rpc = new PlanningPresenterImplTestRpc(&m_ctx);
    QDir pluginDir;
    pluginDir = QDir(qApp->applicationDirPath());
    pluginDir.cdUp();
    pluginDir.cdUp();
    pluginDir.cd(QStringLiteral("plugins"));
    m_applicationPluginManager = new ApplicationPluginManager(pluginDir.absoluteFilePath(QStringLiteral("config.json")),
                                                              pluginDir.absolutePath());
    if (m_applicationPluginManager)
        m_applicationPluginManager->inject(&m_ctx);
    iface = m_ctx.get<ZetaSurgical::PlanningPresenter>();
    if (!iface) {
        iface = new ZetaSurgical::PlanningPresenter;
        m_ctx.store(iface);
    }
    m_ctx.startExecution();
}

void PlanningPresenterInterfaceImplTest ::TearDown()
{
    delete m_applicationPluginManager;
}

TEST_F(PlanningPresenterInterfaceImplTest, editTargetAtIndex)
{

    iface->editTargetAtIndex(-1);
}

TEST_F(PlanningPresenterInterfaceImplTest, deleteTargetAtIndex)
{

    iface->deleteTargetAtIndex(-1);
}

TEST_F(PlanningPresenterInterfaceImplTest, selectTargetAtIndex)
{

    iface->selectTargetAtIndex(-1);
}

TEST_F(PlanningPresenterInterfaceImplTest, targetsList_Imp)
{
    auto oldValue = iface->targetsList();
    auto newValue = new GreenHouse::Model();

    bool changeSignalEmitted = false;
    QObject::connect(iface, &ZetaSurgical::PlanningPresenter::targetsListChanged,
                     [&]() { changeSignalEmitted = true; });

    iface->setTargetsList(newValue);
    ASSERT_TRUE(changeSignalEmitted);
    ASSERT_NE(iface->targetsList(), oldValue);
    ASSERT_EQ(iface->targetsList(), newValue);
}

TEST_F(PlanningPresenterInterfaceImplTest, selectedTargetIndex_Imp)
{
    auto oldValue = iface->selectedTargetIndex();
    auto newValue = std::numeric_limits<int>::max();

    bool changeSignalEmitted = false;
    QObject::connect(iface, &ZetaSurgical::PlanningPresenter::selectedTargetIndexChanged,
                     [&]() { changeSignalEmitted = true; });

    iface->setSelectedTargetIndex(newValue);
    ASSERT_TRUE(changeSignalEmitted);
    ASSERT_NE(iface->selectedTargetIndex(), oldValue);
    ASSERT_EQ(iface->selectedTargetIndex(), newValue);
}
