//--------------------------------------------------------------------------------------------------
// Generated using GreenHouse Modeling Library v 1.6.15
// From: ZetaSurgical LoginPresenter Interface
// Please do not edit this file as it will be overwritten the next time the application flow is
// regenerated.
//--------------------------------------------------------------------------------------------------
#pragma once

#include <limits>

#include <QCoreApplication>

#include <gtest/gtest.h>
#include <gmock/gmock-matchers.h>

#include <QJsonDocument>

#include <applicationpluginmanager.h>

#include <ZetaSurgical/loginpresenter.hpp>

using namespace testing;

class LoginPresenterImplTestRpc : public GreenHouse::RPCServiceInterface
{
public:
    using GreenHouse::RPCServiceInterface::RPCServiceInterface;

    QList<QJsonObject> messages;

    // GreenHouse::RPCServiceInterface interface
protected:
    void sendPayload(const QByteArray &data) override
    {
        QJsonParseError err;
        QJsonDocument doc = QJsonDocument::fromJson(data, &err);
        if (err.error == QJsonParseError::NoError) {
            messages.append(doc.object());
        }
    }
};

class LoginPresenterInterfaceImplTest : public Test
{
    // Test interface
protected:
    void SetUp();
    void TearDown();

    ZetaSurgical::LoginPresenter *iface;
    ApplicationPluginManager *m_applicationPluginManager;
    LoginPresenterImplTestRpc *m_rpc;
    GreenHouse::Context m_ctx;
};

void LoginPresenterInterfaceImplTest ::SetUp()
{
    m_rpc = new LoginPresenterImplTestRpc(&m_ctx);
    QDir pluginDir;
    pluginDir = QDir(qApp->applicationDirPath());
    pluginDir.cdUp();
    pluginDir.cdUp();
    pluginDir.cd(QStringLiteral("plugins"));
    m_applicationPluginManager = new ApplicationPluginManager(pluginDir.absoluteFilePath(QStringLiteral("config.json")),
                                                              pluginDir.absolutePath());
    if (m_applicationPluginManager)
        m_applicationPluginManager->inject(&m_ctx);
    iface = m_ctx.get<ZetaSurgical::LoginPresenter>();
    if (!iface) {
        iface = new ZetaSurgical::LoginPresenter;
        m_ctx.store(iface);
    }
    m_ctx.startExecution();
}

void LoginPresenterInterfaceImplTest ::TearDown()
{
    delete m_applicationPluginManager;
}

TEST_F(LoginPresenterInterfaceImplTest, onUsernameEditRequested)
{

    iface->onUsernameEditRequested();
}

TEST_F(LoginPresenterInterfaceImplTest, onPasswordEditRequested)
{

    iface->onPasswordEditRequested();
}

TEST_F(LoginPresenterInterfaceImplTest, onLoginClicked)
{

    iface->onLoginClicked();
}

TEST_F(LoginPresenterInterfaceImplTest, onUserNameEdited)
{

    iface->onUserNameEdited(QString());
}

TEST_F(LoginPresenterInterfaceImplTest, onPasswordEdited)
{

    iface->onPasswordEdited(QString());
}

TEST_F(LoginPresenterInterfaceImplTest, invalidCredentialsEntered_Imp)
{
    auto oldValue = iface->invalidCredentialsEntered();
    auto newValue = !oldValue;

    bool changeSignalEmitted = false;
    QObject::connect(iface, &ZetaSurgical::LoginPresenter::invalidCredentialsEnteredChanged,
                     [&]() { changeSignalEmitted = true; });

    iface->setInvalidCredentialsEntered(newValue);
    ASSERT_TRUE(changeSignalEmitted);
    ASSERT_NE(iface->invalidCredentialsEntered(), oldValue);
    ASSERT_EQ(iface->invalidCredentialsEntered(), newValue);
}
