//--------------------------------------------------------------------------------------------------
// Generated using GreenHouse Modeling Library v 1.6.15
// From: ZetaSurgical ScanData Interface
// Please do not edit this file as it will be overwritten the next time the application flow is
// regenerated.
//--------------------------------------------------------------------------------------------------
#pragma once

#include <limits>

#include <QCoreApplication>

#include <gtest/gtest.h>
#include <gmock/gmock-matchers.h>

#include <QJsonDocument>

#include <applicationpluginmanager.h>

#include <ZetaSurgical/scandata.hpp>

using namespace testing;

class ScanDataImplTestRpc : public GreenHouse::RPCServiceInterface
{
public:
    using GreenHouse::RPCServiceInterface::RPCServiceInterface;

    QList<QJsonObject> messages;

    // GreenHouse::RPCServiceInterface interface
protected:
    void sendPayload(const QByteArray &data) override
    {
        QJsonParseError err;
        QJsonDocument doc = QJsonDocument::fromJson(data, &err);
        if (err.error == QJsonParseError::NoError) {
            messages.append(doc.object());
        }
    }
};

class ScanDataInterfaceImplTest : public Test
{
    // Test interface
protected:
    void SetUp();
    void TearDown();

    ZetaSurgical::ScanData *iface;
    ApplicationPluginManager *m_applicationPluginManager;
    ScanDataImplTestRpc *m_rpc;
    GreenHouse::Context m_ctx;
};

void ScanDataInterfaceImplTest ::SetUp()
{
    m_rpc = new ScanDataImplTestRpc(&m_ctx);
    QDir pluginDir;
    pluginDir = QDir(qApp->applicationDirPath());
    pluginDir.cdUp();
    pluginDir.cdUp();
    pluginDir.cd(QStringLiteral("plugins"));
    m_applicationPluginManager = new ApplicationPluginManager(pluginDir.absoluteFilePath(QStringLiteral("config.json")),
                                                              pluginDir.absolutePath());
    if (m_applicationPluginManager)
        m_applicationPluginManager->inject(&m_ctx);
    iface = m_ctx.get<ZetaSurgical::ScanData>();
    if (!iface) {
        iface = new ZetaSurgical::ScanData;
        m_ctx.store(iface);
    }
    m_ctx.startExecution();
}

void ScanDataInterfaceImplTest ::TearDown()
{
    delete m_applicationPluginManager;
}
