//--------------------------------------------------------------------------------------------------
// Generated using GreenHouse Modeling Library v 1.6.15
// From: ZetaSurgical NavigationPresenter Interface
// Please do not edit this file as it will be overwritten the next time the application flow is
// regenerated.
//--------------------------------------------------------------------------------------------------
#pragma once

#include <limits>

#include <QCoreApplication>

#include <gtest/gtest.h>
#include <gmock/gmock-matchers.h>

#include <QJsonDocument>

#include <applicationpluginmanager.h>

#include <ZetaSurgical/navigationpresenter.hpp>

using namespace testing;

class NavigationPresenterImplTestRpc : public GreenHouse::RPCServiceInterface
{
public:
    using GreenHouse::RPCServiceInterface::RPCServiceInterface;

    QList<QJsonObject> messages;

    // GreenHouse::RPCServiceInterface interface
protected:
    void sendPayload(const QByteArray &data) override
    {
        QJsonParseError err;
        QJsonDocument doc = QJsonDocument::fromJson(data, &err);
        if (err.error == QJsonParseError::NoError) {
            messages.append(doc.object());
        }
    }
};

class NavigationPresenterInterfaceImplTest : public Test
{
    // Test interface
protected:
    void SetUp();
    void TearDown();

    ZetaSurgical::NavigationPresenter *iface;
    ApplicationPluginManager *m_applicationPluginManager;
    NavigationPresenterImplTestRpc *m_rpc;
    GreenHouse::Context m_ctx;
};

void NavigationPresenterInterfaceImplTest ::SetUp()
{
    m_rpc = new NavigationPresenterImplTestRpc(&m_ctx);
    QDir pluginDir;
    pluginDir = QDir(qApp->applicationDirPath());
    pluginDir.cdUp();
    pluginDir.cdUp();
    pluginDir.cd(QStringLiteral("plugins"));
    m_applicationPluginManager = new ApplicationPluginManager(pluginDir.absoluteFilePath(QStringLiteral("config.json")),
                                                              pluginDir.absolutePath());
    if (m_applicationPluginManager)
        m_applicationPluginManager->inject(&m_ctx);
    iface = m_ctx.get<ZetaSurgical::NavigationPresenter>();
    if (!iface) {
        iface = new ZetaSurgical::NavigationPresenter;
        m_ctx.store(iface);
    }
    m_ctx.startExecution();
}

void NavigationPresenterInterfaceImplTest ::TearDown()
{
    delete m_applicationPluginManager;
}

TEST_F(NavigationPresenterInterfaceImplTest, tabIndex_Imp)
{
    auto oldValue = iface->tabIndex();
    auto newValue = std::numeric_limits<int>::max();

    bool changeSignalEmitted = false;
    QObject::connect(iface, &ZetaSurgical::NavigationPresenter::tabIndexChanged, [&]() { changeSignalEmitted = true; });

    iface->setTabIndex(newValue);
    ASSERT_TRUE(changeSignalEmitted);
    ASSERT_NE(iface->tabIndex(), oldValue);
    ASSERT_EQ(iface->tabIndex(), newValue);
}
